# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
        
build_script:
  - travis-tool.sh install_deps
  
install:
  - ps: Bootstrap
  - Rscript -e "install.packages('desc', repos = 'http://cran.rstudio.com')"
  - Rscript -e "install.packages('remotes', repos = 'http://cran.rstudio.com')"
  - Rscript -e "remotes::install_github('chasemc/electricShine')"


skip_tags: true

environment:
  global:
    WARNINGS_ARE_ERRORS: 0
    PKGTYPE: win.binary 
    appVersion: '1.0.0'
    USE_RTOOLS: true
    
  access_token:
    secure: Tq5+IiRsS/Xt3ksEBWrlso255+m0aQs0LOngGmF9ntbcHFopQul3LZYeCqvGq4CJ
  
  matrix:
  - R_VERSION: 3.6.1
    R_ARCH: x64
    GCC_PATH: mingw_64

matrix:
  fast_finish: true



test_script:
  - travis-tool.sh run_tests



on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

  - path: 'My_App\dist\*.exe'
    name: app



for: 
-
  branches:
    only:
      - master

  before_test:
    - git checkout master
    - Rscript -e "desc::desc_bump_version('patch',list.files(pattern = 'DESCRIPTION', ignore.case = T, recursive = F))"
    - Rscript -e "writeChar(as.character(desc::desc_get_version(list.files(pattern = 'DESCRIPTION', ignore.case = T, recursive = F))), 'version_temp.txt')" 
    - ps: $env:appVersion = Get-Content version_temp.txt 
    - git config --global credential.helper store
    - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
    - git config --global user.email "cclark42@uic.edu"
    - git config --global user.name "Chase Clark"
    - git add DESCRIPTION
    - git commit -m "AppVeyor version bump; [skip appveyor]" 
    - git push origin master
  
  after_test:
    - Rscript -e "electricShine::buildElectricApp(appName = 'My_App', 
                                  packageName = 'My_Demo',
                                  semanticVersion = desc::desc_get_version(list.files(pattern = 'DESCRIPTION', ignore.case = T, recursive = F)),
                                  buildPath = getwd(),
                                  MRANdate = as.character(Sys.Date() - 3), 
                                  functionName = 'run_app', 
                                  githubRepo = 'chasemc/demoApp',
                                  localPath  = NULL,
                                  only64 = TRUE)"
  
  
  deploy:
    provider: GitHub
    auth_token:
      secure: Tq5+IiRsS/Xt3ksEBWrlso255+m0aQs0LOngGmF9ntbcHFopQul3LZYeCqvGq4CJ
    tag: $(appVersion)
    description: ''
    force_update: false
    artifact: app           
    draft: false
    prerelease: false
   
 
